# Generated by Django 3.2.25 on 2024-06-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0002_spin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spin',
        ),
    ]
